name: WF4 - Jobs Outputs

on:
   workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest
    # Job's output
    outputs:
      build-stage: ${{ steps.set-debug-stage.outputs.BUILD_STAGE }}
    
    steps:
      - name: Set debug
        id: set-debug-stage
        run: printf 'BUILD_STAGE=%s\n' "debug" >> $GITHUB_OUTPUT
  
  report: 
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get stage
        run: printf 'The build stage is %s\n' "${{ needs.setup.outputs.build-stage }}"
