name: WF6 - Artifacts upload

on:
   workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6  
      - run: |
         mkdir -p path/to/artifact
         pwd
         printf '%s\n' "Hello" > path/to/artifact/world.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6 
        with:
          # Artifact name
          name: my-first-artifact
          # A file, directory or wildcard pattern that describes what to upload
          # a file
          path: path/to/artifact/world.txt
          # a whole directory
          #path: path/to/artifact/

